development:
  adapter: postgresql
  database: development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: production
  pool: 5
  timeout: 5000