development:
  adapter: postgresql
  database: development
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

# test:
#   adapter: postgresql
#   database: test
#   pool: 5
#   timeout: 5000

production:
  adapter: postgresql
  database: production
  pool: 5
  timeout: 5000