Team.create(abbr: "JDUB", name: "Joker's Wild")
Team.create(abbr: "KEDZ", name: "Elko Bugles")
Team.create(abbr: "GS",   name: "General Salami")
Team.create(abbr: "PBT",  name: "Philadelphia BallTappers")
Team.create(abbr: "COD",  name: "Cod Brind'amour")
Team.create(abbr: "SKUL", name: "Uni VOLTINES")
Team.create(abbr: "FOI",  name: "Foxes On Ice")
Team.create(abbr: "NOLO", name: "PATRICK'S DIVISION")
Team.create(abbr: "CUP",  name: "That's Why We Fucking Play")
Team.create(abbr: "SDET", name: "SD Belle")
Team.create(abbr: "RUBE", name: "No Gudas Smash")
Team.create(abbr: "wahh", name: "boring uninspired")
